// AUTOGENERATED - DO NOT MODIFY
import ReportView from '../src/views/ReportView';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2026-02-04 18:13:26.043342 +0100 CET m=+0.395447460';

export { 
  ReportView	
 };

export default {
  "app_backend": {
    "webhooks": []
  },
  "connect_permissions": null,
  "icon": "",
  "id": "com.stripe.icplus-sim-report",
  "name": "IC+ Fee Simulator",
  "permissions": [
    {
      "permission": "report_runs_and_report_types_read",
      "purpose": "Read report run status and results"
    },
    {
      "permission": "report_runs_and_report_types_write",
      "purpose": "Create activity report runs"
    },
    {
      "permission": "file_read",
      "purpose": "Download report files"
    }
  ],
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "http://localhost:4243"
      ],
      "image-src": null,
      "purpose": ""
    },
    "views": [
      {
        "component": "ReportView",
        "viewport": "stripe.dashboard.home.overview"
      }
    ]
  },
  "version": "0.0.1"
};
